### ISSUE TITLE
implementing posixToParts function

### ISSUE THREAD

**Issue by JolandaNava** [justinmimbs/time-extra#1]
Would you see the use in implementing a function that takes a Posix and converts it to the `Parts` datatype?

`posixToParts : Posix -> Parts`

I can see many scenarios where having a single function returning all the values stored in `Parts` would be more convenient than having to derive them one at the time using the functions in the `Time` module.

For instance, I am writing something that requires grouping elements by date using `groupWhile` (eg. from a list of elements with a timestamp, get a list of lists where each sublist has elements belonging to the same date). Converting to a `Posix` to `Parts` would make the comparison code a little neater. 

Happy to send in a PR if you think this would be a useful addition.

**Comment by justinmimbs** [comment]
Hi Jolanda,

Sure, I think a `posixToParts` function could be added. It's a nice dual to `partsToPosix`, but I do think its use cases should be rare.

In your example, you would ignore the four clock-time fields in `Parts`, so a more efficient approach would be to compare the year, month, and day values one at a time, using the functions in `Time` as you described. And you could make this read nicely by using a helper function like `sameDate : Zone -> Posix -> Posix -> Bool`. Anyway, just a thought, since `posixToParts` sounds like overkill for the example you mentioned. 😅 

If you're keen to, then, yes, please submit a PR!

Thanks,

Justin

**Comment by JolandaNava** [comment]
Yes I think you're right, I ended up using a similar approach and might change the implementation of `sameDate` if I can come up with a better approach. For now I sent in the PR :)
