### ISSUE TITLE
diff says that 1 month minus 1 day is in the same month

### ISSUE THREAD

**Issue by BrianHicks** [justinmimbs/time-extra#4]
If I ask for the month-level diff between August 28, 2019 and September 27, 2019, I get `0` instead of `1`. This seems to work with any combination where the delta is exactly one month minus one day (e.g. Jan 1 to Feb 2, April 26 to May 25, etc.)

Here's an Ellie with a SSCCE: https://ellie-app.com/6vLwxJLLRbVa1

**Comment by justinmimbs** [comment]
Hi Brian,

This is the intended behavior. The diff function is meant to count whole intervals, so in the case of months, one month is the time between same days of the month (e.g. the 15th to the next 15th); it’s not always the number of boundaries crossed. The example in the docs is meant to illustrate this (I should clarify with a note).

So the diff in months between August 28 and any time less than September 28 should also be 0.

Other intervals work this way too; e.g. the diff in hours between 10:30:00 and 11:29:59 is also 0.

It sounds like you expected the function to count boundary crossings? (I implemented diff this way because I’ve found that when I needed to diff times I usually wanted a count of whole intervals rather than boundary crossings; however, I know this is subjective, and I can imagine the utility of a count of boundary crossings.) Are you able to work with the current version of diff or are you looking for a boundary crossing version?

Thanks,

Justin

**Comment by BrianHicks** [comment]
In my case, this caused a bug—we assumed that boundary crossings would count, so students saw their assignments were due "yesterday" instead of "29 days from now". Whoops! We were just saying `sameMonth d = diff Month zone reference d == 0` so I was able to get unblocked by comparing `Time.toMonth` values.

I don't have a super strong opinion about whether or not `diff` needs to count boundary crossings, but I would not have guessed that it didn't. I now see you say "whole intervals" in the docs, but I do not see that in my editor while writing code. If you'd like to just close this as "working as intended" that's a fine outcome by me. A better name might help, but I do not have any suggestions, sorry!

**Comment by justinmimbs** [comment]
If you did need to count boundary crossings, then you could floor both times to the appropriate interval and diff those. If the diff is 0, then they are within the same interval.

The diff function is intended to make it easier to write a relative-time function than a boundary crossing version would. You can check the diff in years; if it’s 0 then check the diff in months; if it’s 0 then check weeks; if it’s 0 then check days; etc. You can’t do that with a diff function that only counts boundary crossings.

Hope that helps!

**Comment by BrianHicks** [comment]
ooh, that sounds like a much better way to do what we're doing. Thank you!

**Comment by justinmimbs** [comment]
Great! Sure thing. 😄
